apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: {{ include "transmission-daemon.fullname" . }}-tcp
  labels:
    {{- include "transmission-daemon.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: {{ .Values.ports.web_port }}
    protocol: TCP
    targetPort: http
  - name: tcp
    port: {{ .Values.ports.tcp_port }}
    protocol: TCP
    targetPort: tcp
  type: ClusterIP
  selector:
    {{- include "transmission-daemon.selectorLabels" . | nindent 4 }}
