apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: {{ include "postgres.fullname" . }}-tcp
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: tcp
  type: ClusterIP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}