# Default values for transmission-daemon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: funkycode/transmission-daemon
  tag: v3.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

appVolumeMounts:
  data:
    emptyDir: true
    mountPath: "/mnt/data"
